### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by KlausVigo** [emmanuelparadis/ape#88] opened 2023-06-16 08:29 UTC
Thanks @KlausVigo !

> In some cases having access to `trim.internal=FALSE` might be exactly what's intended with this pull request. Emmanuel, I can make a pull request if you want. 

Yes, sometimes but not always. This function that I wrote is the result of a lot of testing of different scenarios. I wrote more here too:  https://hedvigsr.tumblr.com/post/676182151636647936/pruning-to-nodes-and-keeping-tips

_Originally posted by @HedvigS in https://github.com/emmanuelparadis/ape/issues/87#issuecomment-1593326554_

**Comment by HedvigS** [comment] 2023-06-16 09:25
( This i sort of a duplicate of #48 ;) )

**Closed** 2023-06-16 09:29 UTC

**Comment by KlausVigo** [comment] 2023-06-16 09:30
Sorry I seem to have clicked before I finished a post. Now my comments are at your pull request.

**Comment by HedvigS** [comment] 2023-06-16 10:10
no worries :D!
